name: Comment on Discussion When Dist Files Change

on:
  push:
    branches:
      - main
    paths:
      - "sdata/dist/**"
      - "!sdata/dist/**/README.md"

jobs:
  comment_on_discussion:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository == 'Kioro404/dots-hyprland'
    steps:
      - name: Create comment on discussion
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCUSSION_NUMBER: 1
        run: |
          # 5. ACTUALIZACIÓN: Nuevo mensaje en inglés y multiplataforma
          MESSAGE="### 🚀 Installation Script Update\n\n"
          MESSAGE+="A new change has been detected in the distribution assets.\n\n"
          MESSAGE+="* **Commit HASH:** \`${{ github.sha }}\` \n"
          MESSAGE+="* **Change Log:** ${{ github.event.head_commit.message }}\n\n"
          MESSAGE+="---"
          
          REPO_OWNER="${{ github.repository_owner }}"
          REPO_NAME="${{ github.event.repository.name }}"

          DISCUSSION_NODE_ID=$(gh api graphql -f query='
            query {
              repository( owner: "'${REPO_OWNER}'", name: "'${REPO_NAME}'" )
                { discussion(number: '${DISCUSSION_NUMBER}') { id } } 
              }' | \
            jq -r '.data.repository.discussion.id')
          gh api graphql -f query='
            mutation {
              addDiscussionComment(input:{
                discussionId: "'$DISCUSSION_NODE_ID'",
                body: "'"$MESSAGE"'",
              }) {
                clientMutationId
                comment {
                  id
                  body
                }
              }
            }
          '